### ISSUE TITLE
Example in README doesn't work :(

### ISSUE THREAD

**Issue by khanghoang** [tungv/redux-api-call#1]
Tried to follow but couldn't get it work.
![image](https://cloud.githubusercontent.com/assets/3213579/19222159/0edb4a10-8e7c-11e6-883c-754dbf7bd209.png)

**Comment by tungv** [comment]
Yeah, thank you for reporting. I found that that example isn't a really good one. Before the first successful call, data is always `null`, so when that selector is called, the exception in your screenshot will arise.

To make it work, you can try to do something like this instead:

``` js
import { flow, get, filter } from 'lodash/fp';

const { dataSelector } = makeFetchAction(/* your actual config */);

export const completeTodos = flow(
  dataSelector,
  get('todos'),
  filter(todo => todo.complete)
);
```

if you want a better solution with array memoization, try this:

``` js
import { createSelector } from 'reselect';
import { flow, get, filter } from 'lodash/fp';

const { dataSelector } = makeFetchAction(/* your actual config */);

const todosSelector = flow(dataSelector, get('todos'));
const completeTodos = createSelector(todosSelector, filter(todo => todo.complete));
```

**Comment by tungv** [comment]
this issue is a good reason to remove custom selector altogether from this library and delegate it to other awesome libs like `reselect` and `lodash`

**Comment by khanghoang** [comment]
@tungv thanks for your response 👍
