### ISSUE TITLE
Not dispatch FETCH_FAILURE on 404 response

### ISSUE THREAD

**Issue by TanNguyenUIT** [tungv/redux-api-call#14]
When I create a fetch action to a url that does not exist on the server handle, I do not get the FETCH_FAILURE action, then I can't handling side effect if only the FETCH_START action.

<img width="866" alt="screen shot 2017-03-12 at 11 32 53 am" src="https://cloud.githubusercontent.com/assets/17514591/23829056/731e35ae-0718-11e7-9a40-52dbc41a60c2.png">
<img width="866" alt="screen shot 2017-03-12 at 11 33 14 am" src="https://cloud.githubusercontent.com/assets/17514591/23829058/7e825038-0718-11e7-9ecf-dae0622d8995.png">
<img width="205" alt="screen shot 2017-03-12 at 11 33 31 am" src="https://cloud.githubusercontent.com/assets/17514591/23829061/86bf238e-0718-11e7-921e-e44b8af4c54f.png">

**Comment by tungv** [comment]
I could see why. Because the response is not an `applicstion/json` content. And this lib **currently** only supports json. I have a plan to support or at least notify you when the response is not a valid json.

**Comment by khanghoang** [comment]
@TanNguyenUIT @tungv is there anything I can help here? Should we change the `defaultAdapter` in this case?

**Comment by khanghoang** [comment]
@TanNguyenUIT I think in the meantime, you can use this code.  
```
  const storeEnhancers = compose(
    // initialValue
    applyMiddleware(
      // middlewares go here
      apiMiddleware(({ endpoint, ...others }) => fetch(endpoint, others)
        .then(res => Promise.resolve({
          ok: res.ok,
          json() {
            return res.json().then(
              json => json,
              err => new Error(`Error when parsing ${err}`),
            );
          },
        }))
      ),
  );
```

**Comment by tungv** [comment]
Looks good @khanghoang. Just a note: when upgrading to the new version, adapter API might change

**Comment by TanNguyenUIT** [comment]
@tungv Thank you very much for the early reply to my problem. 
@khanghoang Thank you very much for sharing the code that helped solve my problem. It is working.

**Comment by tungv** [comment]
Awesome @TanNguyenUIT. I will notify you when i publish the next beta version

**Comment by tungv** [comment]
the beta version is released. You can install it using `npm i -S redux-api-call@beta`. Migration path is extremely straight-forward and can be found here https://github.com/tungv/redux-api-call/wiki/Migration-to-V1.

cc @TanNguyenUIT @khanghoang
