### ISSUE TITLE
1.0 ROADMAP

### ISSUE THREAD

**Issue by tungv** [tungv/redux-api-call#16]
A few things I want to accomplish before releasing an official 1.0.0 milestone.

1. export the default middleware as `middleware`, so you don't have to invoke it inside `applyMiddlewares` function
2. export a `createMiddleware(adapter)` for folks that need it
3. adapter API should be able to access getState
4. default adapter should be able to handle non-json response

**Comment by tungv** [comment]
Server side rendering support?

```js

export const resolver = (store, ...params) => {
  return new Promise((resolve, reject) => {
    store.dispatch(actionCreator(...params))
    const unsubscribe = store.subscribe(() => {
      const data = dataSelector(store.getState());
      const error = errorSelector(store.getState());
      if (data || error) {
        unsubscribe();
        if (data) resolve(data) else reject(error);
      }
    })
  })
}
```

**Comment by tungv** [comment]
adapter api might look like this (just write out of my head)

```js
const apiMiddleware = createApiMiddleware(async (request, getState) => {
  const authHeader = request.headers.Authentication || `Bearer: ${tokenSelector(getState())}`
  const { endpoint, ...others } = request;

  const resp = await fetch(endpoint, {
    ...others,
    headers: {
      ...others.headers,
      Authorization: authHeader,
    },
  });

  return resp.json()
});
```

@tvkhoa @khanghoang what do you guys think?

**Comment by tungv** [comment]
maybe we can even add a middleware layer for apiMiddleware 🦄 

```js
const apiMiddleware = createApiMiddleware(compose(
  applyQueryString,
  applyJsonBody,
  addTokenHeader,
  fetchAndReturnJson,
))
```

example:

```js
const applyQueryString = (next) => (req, getState) => {
  if (req.query) {
    const { endpoint, query, ...others } = req;
    const [path, existingQuery] = endpoint.split('?');
    const finalQuery = existingQuery
       ? { ...qs.parse(existingQuery), ...query } 
       : query;

    const finalEndpoint = `${path}?${qs.stringify(finalQuery)}`
    return next({
      endpoint: finalEndpoint,
      ...others,
    }, getState);
  }

  // nothing to do here
  return next(req, getState);
};
```

**Comment by tvkhoa** [comment]
Agree with 1, 3 and 4.

I'm not sure about 2. Instead of that, I think it's better if we can export `adapterCreator` which already include 4 inside.

```javascript
const adapter = adapterCreator({
   headers: {
    'Token': 'abcde',
  }
})
```

or

```javascript
const adapter = adapterCreator({
   headers: (state) => ({
     'Token': tokenSelector(state),
  })
})
```

**Comment by tvkhoa** [comment]
For your last comment, personally I think we don't need it. User can (and should) handle it in makeFetchAction

**Comment by tvkhoa** [comment]
And one more thing, for now, we handle sequence of actions (after fetch success, dispatch sth) by epic or check ACTION.SUCCESS inside reducer.

But I think not all people like to do that. they still want a callback after a success (or fail) fetch. Should we add it in `makeFetchAction` ?
The idea is:

```javascript
makeFetchAction(
  'TODO_LIST',
  ({ page, limit }) => ({
    endpoint: `/api/v1/todos?page=${page}&limit=${limit}`,
    method: 'GET',
  }),
  {
   pending: (dispatch, getState) => {},
   success: (dispatch, getState) => {},
   fail: (dispatch, getState) => {},
  }
);
```

**Comment by tungv** [comment]
@tvkhoa
Regard to item no 2: adapter can send request via different mechanisms (like $.ajax or fetch or superagent, etc.) we don't limit this options here. They might want only use XML over SOAP and don't care about JSON at all.

If they just want a simple configuration, they (or we) can provide a function that take those params and return an adapter. Function is always the most powerful tool.

regard to handling `query` and `body` in makeFetchAction: This is impossible to know what the resolved values are unless the actions get to api middleware (where values as functions are actually invoked)

regarding to adding callbacks to `makeFetchAction`, I think if it can be done where else, but different methods, let's keep it out there. I prefer not to expose more APIs (or: keep it systematically simple)

**Comment by tungv** [comment]
I think we should get started this weekend. New Adapter API is a primary updates, it will ease the other steps significantly.

**Comment by tvkhoa** [comment]
@tungv what is the plan for removing Rxjs ?

**Comment by tungv** [comment]
I don't know actually. But why do we want to remove it?

**Comment by tvkhoa** [comment]
Because not all people use RxJS.
And concept of redux-api-call is good itself. I remember before we applied Rxjs, it had worked well.

**Comment by tungv** [comment]
it wasn't able to handle dropped requests. If the reason is the installation line require rxjs. then we can move rxjs to dependencies instead of peer. After that, we can freely reimplement the core the way we want

**Comment by tvkhoa** [comment]
Agree with you. Let's keep it first.

**Comment by tungv** [comment]
it's done. 1.0.0 has been released
