### ISSUE TITLE
Using Symbol.for('CALL_API') instead of Symbol('CALL_API')

### ISSUE THREAD

**Issue by khanghoang** [tungv/redux-api-call#22]
The problem: 
- In some cases, I want to get your RAC (redux-api-call) object in middleware, but it's impossible because it uses a symbol as its key. 

Solution:
- Instead of using Symbol('CALL_API'), we should change to use Symbol.for('CALL_API') so that if we want to get that symbol at runtime, we can call Symbol.for('CALL_API').

FYI: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for

cc: @tvkhoa @tungv

**Comment by tungv** [comment]
I'm not sure why you want to access the action. It is NOT an action (at least a standard action) so no other party should be aware of its existence. I'm pretty sure that redux api call v1 can solve your use case

**Comment by khanghoang** [comment]
@tvkhoa will love this

**Comment by tungv** [comment]
This protects us from doing the wrong things. Exporting action creators that need a specific middleware is wrong. What if I export a thunk action creator that return an array of promises? Embed business logic in shared lib is wrong, you will end up adding if-else all the place.

**Comment by tvkhoa** [comment]
Why it's wrong? Think about some libraries that follow redux principal. Example redux-react-router, they have a set of action creators that help you to interact with location and history. You can not use them without their middleware, right?
From the user perspective, it's nice to have ability to protect us from doing wrong things, but more important, we need the flexibility and ability to solve our problems. Here, it depends on our architecture and we decide to export the AC to use somewhere else.

**Comment by tungv** [comment]
Their action creator are exported from their package. Are you exporting redux api call action creators from redux api call package?

**Comment by tvkhoa** [comment]
I'm exporting the result of makeStateAction which comes from redux-api-call

**Comment by tungv** [comment]
So that is the difference between libs (no implied business logic) and apps (has business logic). There is no point to compare your app and react router redux.

Btw, can you describe your problem here?

**Comment by tungv** [comment]
close this as Symbol is removed in 1.0.3

**Comment by tungv** [comment]
CALL_API is actually removed altogether in 1.0.4
