### ISSUE TITLE
Unknown plugin "transform-function-bind" specified in '.../node_modules/redux-api-call/.babelrc'

### ISSUE THREAD

**Issue by lannablue89** [tungv/redux-api-call#27]
Hi @tungv ,

I have a problem when add your lib to my project. It show error when I run yarn start
Unknown plugin "transform-function-bind" specified in '.../node_modules/redux-api-call/.babelrc'
How can I fix it?

**Comment by khanghoang** [comment]
@lannablue89 removing '.../node_modules/redux-api-call/.babelrc' file did the trick for me

**Comment by tungv** [comment]
I think that plugin need to be removed from babelrc. I guess the way react native bundles it is different from webpack default config

**Comment by tungv** [comment]
@lannablue89 can you try install v1.0.6 to see if it works?
