### ISSUE TITLE
Why no action for reset

### ISSUE THREAD

**Issue by thien-do** [tungv/redux-api-call#49]
https://github.com/tungv/redux-api-call/blob/6273d2942bad9f1c833c3d623632bb39f2e292a3/packages/core/src/constants.js#L6

https://github.com/tungv/redux-api-call/blob/6273d2942bad9f1c833c3d623632bb39f2e292a3/packages/core/src/index.js#L8-L14

**Comment by tungv** [comment]
PR is welcome

**Comment by tungv** [comment]
closed in #50
