### ISSUE TITLE
Is that safe to use `isInvalidatedSelector`?

### ISSUE THREAD

**Issue by hanh090** [tungv/redux-api-call#68]
I am working in a feature which needed using `isInvalidatedSelector`, one of my concern is it was export but nowhere in documentation mentioned about that. After tracing down, I see in this commit (https://github.com/tungv/redux-api-call/commit/4c6159d892d79adcf041fa35808b4af52302a2bf) you was removed `isInvalidatedSelector` from `README`. Can I know the reason behind? And is it safe to use this prop in production?

**Comment by tungv** [comment]
hi Hanh, it's safe to use it as per https://github.com/tungv/redux-api-call/blob/master/packages/core/src/makeFetchAction.js#L69

Glad that you find this useful. Would you like to improve the documentation for this project?

**Comment by hanh090** [comment]
no problem anh
