### ISSUE TITLE
Using symbol for action type is good. But I cannot reuse in another project

### ISSUE THREAD

**Issue by tvkhoa** [tungv/redux-api-call#7]
I'm having webapp using redux-api-call and now I need port it to a react-native project (which is using redux-api-call too )

The idea is reusing all actionCreators, reducers and selectors. So, I exported all of them and imported it into react-native project.

But because of the symbol, I cannot reuse the actionCreators created by redux-api-call. 
```
if (!action[CALL_API]) { // The CALL_API in 2 projects is different
       next(action);
       return;
 }
```
Should we remove the symbol and named it by a unique string such as TUNGVU_AWESOME_CALL_API ?

**Comment by tungv** [comment]
Hi @tvkhoa, thank you for writing up an issue report.
I plan to remove symbol in the source code as well. Meanwhile you can try to add some Symbol polyfill to make react native to work.

some good ones here:

https://github.com/medikoo/es6-symbol
https://github.com/zloirock/core-js

However, Symbol is an essential part of the to-be-standard Observable interface. You might consider that case as well. Rxjs is using this lib: https://github.com/blesh/symbol-observable (which has 2M monthly download)

**Comment by tungv** [comment]
I think I understand more of your concern. It's about having 2 different instance of CALL_API symbol, right? I don't understand 2 things:
1. why do we need to have 2 different instances and,
2. what role react-native is in the issue?

**Comment by tungv** [comment]
this will be addressed soon. I will simplify the request pipeline
