### ISSUE TITLE
[React Native] Crash app when request timeout

### ISSUE THREAD

**Issue by khanghoang** [tungv/redux-api-call#8]
### Describe:
- Request timeout when there is no connection.

### Expect:
- Throw error about request timeout but don't crash the app

### Actual:
- App crashs  

The root cause IMO is because we haven't `catch`ed when we create stream from promise.

### Log
```
TypeError: Network request failed
  at this(/xxx/node_modules/whatwg-fetch/fetch.js:441:29)
  at this(/xxx/node_modules/raven-js/src/raven.js:274:34)
```

**Comment by khanghoang** [comment]
fixed by this https://github.com/tungv/redux-api-call/commit/e0102a1a4dfcfdc0fdc8bc0722a3e3924a5be060

**Comment by tungv** [comment]
Awesome
